name: 🐛 Bug Report
description: Create a bug report to help us improve ShopSphere
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us quickly address the issue.

  - type: input
    id: page
    attributes:
      label: Page/Feature Location
      description: Where in ShopSphere did you encounter this issue?
      placeholder: "Example: Product listing page, Cart, Checkout"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is
      placeholder: "Tell us what happened"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Tell us what should have happened"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop screenshots here"

  - type: checkboxes
    id: existing_issue
    attributes:
      label: Existing Issue Check
      description: Confirm if you’ve searched for existing issues before submitting
      options:
        - label: I have searched for existing issues
      validations:
        required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: Agree to abide by the project’s code of conduct
      options:
        - label: I agree to follow the code of conduct
      validations:
        required: true

  - type: checkboxes
    id: contributor_status
    attributes:
      label: Contributor Status
      description: Let us know if you are part of SWOC or IWOC
      options:
        - label: I am a SWOC contributor
        - label: I am an IWOC contributor
        - label: Neither
      validations:
        required: true
