name: 📚 Documentation
description: Report an issue related to documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of documentation issue
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Unclear documentation
        - Incorrect documentation
        - Outdated documentation
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs to be improved?
      placeholder: "README.md, API docs, etc."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be updated or fixed
      placeholder: "The installation instructions are missing..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: If you have specific suggestions for improvements, please provide them
      placeholder: "The documentation should include..."

  - type: checkboxes
    id: existing_issue
    attributes:
      label: Existing Issue Check
      description: Confirm if you’ve searched for existing issues before submitting
      options:
        - label: I have searched for existing issues
    validations:
      required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: Agree to abide by the project’s code of conduct
      options:
        - label: I agree to follow the code of conduct
    validations:
      required: true

  - type: checkboxes
    id: contributor_status
    attributes:
      label: Contributor Status
      description: Let us know if you are part of SWOC or IWOC
      options:
        - label: I am a SWOC contributor
        - label: I am an IWOC contributor
        - label: Neither
    validations:
      required: true
