name: 💡 Feature Request
description: Suggest an idea for ShopSphere
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of ShopSphere does this feature relate to?
      options:
        - User Interface
        - Shopping Cart
        - Payment System
        - Product Management
        - User Authentication
        - Admin Panel
        - Search/Filter
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Which part of ShopSphere does this feature lies in or will affect?
      options:
        - Frontend
        - Backend
        - Both
        - Other
    validations:
      required: true

  - type: checkboxes
    id: existing_issue
    attributes:
      label: Existing Issue Check
      description: Confirm if you’ve searched for existing issues before submitting
      options:
        - label: I have searched for existing issues
    validations:
      required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: Agree to abide by the project’s code of conduct
      options:
        - label: I agree to follow the code of conduct
    validations:
      required: true

  - type: checkboxes
    id: contributor_status
    attributes:
      label: Contributor Status
      description: Let us know if you are part of SWOC or IWOC
      options:
        - label: I am a SWOC contributor
        - label: I am an IWOC contributor
        - label: Neither
    validations:
      required: true
